### ISSUE TITLE
some errors

### ISSUE THREAD

**Issue by yesC48** [ZielonyTrojkat/Frozen-Farlands#37]
thought you'd like to see these (and in turn get them fixed)

`[E] rhino.JavaScriptException: Error: Module "planet" not found. (moon-mod/main.js#3)
	at rhino.ScriptRuntime.throwError(ScriptRuntime.java:37)
	at rhino.module.Require.getModule(Require.java:37)
	at rhino.module.Require.getExportedModuleInterface(Require.java:61)
	at rhino.module.Require.call(Require.java:123)
	at rhino.optimizer.OptRuntime.callName(OptRuntime.java:9)
	at rhino.gen.moon_mod_main_js_8._c_anonymous_1(moon-mod/main.js:3)
	at rhino.gen.moon_mod_main_js_8.call(Unknown Source:41)
	at rhino.optimizer.OptRuntime.call0(OptRuntime.java:3)
	at rhino.gen.moon_mod_main_js_8._c_script_0(moon-mod/main.js:4)
	at rhino.gen.moon_mod_main_js_8.call(Unknown Source:35)
	at rhino.ContextFactory.doTopCall(ContextFactory.java:1)
	at rhino.ScriptRuntime.doTopCall(ScriptRuntime.java:34)
	at rhino.gen.moon_mod_main_js_8.call(Unknown Source:18)
	at rhino.gen.moon_mod_main_js_8.exec(Unknown Source:10)
	at rhino.Context.evaluateString(Context.java:7)
	at mindustry.mod.Scripts.run(Scripts.java:3)
	at mindustry.mod.Scripts.run(Scripts.java:1)
	at mindustry.mod.Mods.lambda$loadScripts$24(Mods.java:92)
	at mindustry.mod.Mods.$r8$lambda$NnKC74spdDGJ9Bm6VvtpC-jIyzo(Mods.java:1)
	at mindustry.mod.Mods$$ExternalSyntheticLambda2.get(R8$$SyntheticClass:16)
	at arc.struct.Seq.each(Seq.java:1)
	at mindustry.mod.Mods.eachEnabled(Mods.java:12)
	at mindustry.mod.Mods.loadScripts(Mods.java:17)
	at mindustry.ClientLauncher.lambda$setup$4(ClientLauncher.java:3)
	at mindustry.ClientLauncher.$r8$lambda$iJ-6sZ_ACwQARuCa-MLy6VoTzXg(ClientLauncher.java:1)
	at mindustry.ai.RtsAI$$ExternalSyntheticLambda0.run(R8$$SyntheticClass:86)
	at arc.assets.AssetManager$1.loadSync(AssetManager.java:3)
	at arc.assets.AssetLoadingTask.handleAsyncLoader(AssetLoadingTask.java:59)
	at arc.assets.AssetLoadingTask.update(AssetLoadingTask.java:17)
	at arc.assets.AssetManager.updateTask(AssetManager.java:15)
	at arc.assets.AssetManager.update(AssetManager.java:5)
	at arc.assets.AssetManager.update(AssetManager.java:9)
	at mindustry.ClientLauncher.update(ClientLauncher.java:76)
	at arc.backend.android.AndroidGraphics.onDrawFrame(AndroidGraphics.java:132)
	at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1571)
	at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1270)

[E] [moon-mod/main.js]: JavaScriptException: Error: Module "planet" not found. (moon-mod/main.js#3)
[I] Time to initialize modded scripts: 693.3053
[W] [ATG.hjson]: Ignoring unknown field: flameRadius (DrawCrucibleFlame)
[W] [Alectro.hjson]: Ignoring unknown field: burstSpacing (PowerTurret)
[W] [Alectro.hjson]: Ignoring unknown field: shots (PowerTurret)
[W] [Alectro.hjson]: Ignoring unknown field: recoilAmount (PowerTurret)
[W] [Defragmentation.hjson]: Ignoring unknown field: burstSpacing (PowerTurret)
[W] [Defragmentation.hjson]: Ignoring unknown field: shots (PowerTurret)
[W] [Defragmentation.hjson]: Ignoring unknown field: recoilAmount (PowerTurret)
[W] [Defragmentation.hjson]: Ignoring unknown field: firstShotDelay (LaserBulletType)
[W] [Defragmentation.hjson]: Ignoring unknown field: shotDelay (LaserBulletType)
[W] [Dragonfly.hjson]: Ignoring unknown field: drawOutlines (ItemTurret)
[W] [Dragonfly.hjson]: Ignoring unknown field: burstSpacing (ItemTurret)
[W] [Dragonfly.hjson]: Ignoring unknown field: shots (ItemTurret)
[W] [Dragonfly.hjson]: Ignoring unknown field: recoilAmount (ItemTurret)
[W] [Dragonfly.hjson]: Ignoring unknown field: heigth (BasicBulletType)
[W] [Fortress-music.hjson]: Ignoring unknown field: isAir (LogicBlock)
[W] [Fortressspeaker.hjson]: Ignoring unknown field: pause (GenericCrafter)
[W] [Frostbite.hjson]: Ignoring unknown field: recoilAmount (LaserTurret)
[W] [Frostbite.hjson]: Ignoring unknown field: restitution (LaserTurret)
[W] [Getharspeaker.hjson]: Ignoring unknown field: pause (GenericCrafter)
[W] [Ghetar-music.hjson]: Ignoring unknown field: isAir (LogicBlock)
[W] [Leech.hjson]: Ignoring unknown field: burstSpacing (ContinuousTurret)
[W] [Leech.hjson]: Ignoring unknown field: shots (ContinuousTurret)
[W] [Leech.hjson]: Ignoring unknown field: recoilAmount (ContinuousTurret)
[W] [Leech.hjson]: Ignoring unknown field: length (PointLaserBulletType)
[W] [Leech.hjson]: Ignoring unknown field: width (PointLaserBulletType)
[W] [MoonRay.hjson]: Ignoring unknown field: burstSpacing (PowerTurret)
[W] [MoonRay.hjson]: Ignoring unknown field: shots (PowerTurret)
[W] [MoonRay.hjson]: Ignoring unknown field: recoilAmount (PowerTurret)
[W] [Pike.hjson]: Ignoring unknown field: burstSpacing (PowerTurret)
[W] [Pike.hjson]: Ignoring unknown field: shots (PowerTurret)
[W] [Pike.hjson]: Ignoring unknown field: recoilAmount (PowerTurret)
[W] [Restart-missle.hjson]: Ignoring unknown field: shootEffect (Weapon)
[W] [Restart-missle.hjson]: Ignoring unknown field: despawnHit (Weapon)
[W] [Restart-missle.hjson]: Ignoring unknown field: despawnEffect (Weapon)
[W] [Restart.hjson]: Ignoring unknown field: burstSpacing (ItemTurret)
[W] [Restart.hjson]: Ignoring unknown field: shots (ItemTurret)
[W] [Restart.hjson]: Ignoring unknown field: smoothReloadSpeed (ItemTurret)
[W] [Restart.hjson]: Ignoring unknown field: hidden (ItemTurret)
[W] [Solar-music.hjson]: Ignoring unknown field: isAir (LogicBlock)
[W] [Solarspeaker.hjson]: Ignoring unknown field: pause (GenericCrafter)
[W] [Stinger.hjson]: Ignoring unknown field: shots (ItemTurret)
[W] [Stinger.hjson]: Ignoring unknown field: spread (ItemTurret)
[W] [Stinger.hjson]: Ignoring unknown field: recoilAmount (ItemTurret)
[W] [Stinger.hjson]: Ignoring unknown field: restitution (ItemTurret)
[W] [Stormer.hjson]: Ignoring unknown field: basePrefix (ItemTurret)
[W] [Tide.hjson]: Ignoring unknown field: spread (ShootPattern)
[W] [Zap.hjson]: Ignoring unknown field: burstSpacing (ItemTurret)
[W] [Zap.hjson]: Ignoring unknown field: shots (ItemTurret)
[W] [Zap.hjson]: Ignoring unknown field: recoilAmount (ItemTurret)
[W] [Zilo.hjson]: Ignoring unknown field: sectorSize (Planet)
[W] [aerogel-factory.hjson]: Ignoring unknown field: suffix (DrawLiquidTile)
[W] [aerogel.hjson]: Ignoring unknown field: type (Item)
[W] [aluminium-foundry.hjson]: Ignoring unknown field: generateEffectRange (GenericCrafter)
[W] [aluminium-foundry.hjson]: Ignoring unknown field: effectChance (GenericCrafter)
[W] [aluminium-foundry.hjson]: Ignoring unknown field: generateEffect (GenericCrafter)
[W] [aluminium.hjson]: Ignoring unknown field: type (Item)
[W] [arcalith-mixer.hjson]: Ignoring unknown field: suffix (DrawLiquidTile)
[W] [arcalith-synthesizer.hjson]: Ignoring unknown field: suffix (DrawLiquidTile)
[W] [arcalith.hjson]: Ignoring unknown field: cache (Liquid)
[W] [arcanite.hjson]: Ignoring unknown field: type (Item)
[W] [arcanthium-missile.hjson]: Ignoring unknown field: shootEffect (Weapon)
[W] [arcanthium-missile.hjson]: Ignoring unknown field: despawnHit (Weapon)
[W] [arcanthium-missile.hjson]: Ignoring unknown field: despawnEffect (Weapon)
[W] [arcanthium.hjson]: Ignoring unknown field: type (Item)
[W] [axoflare4.hjson]: Ignoring unknown field: shootSoundVolume (Weapon)
[W] [axoflare5.hjson]: Ignoring unknown field: heigth (BasicBulletType)
[W] [bauxite.hjson]: Ignoring unknown field: type (Item)
[W] [burner.hjson]: Ignoring unknown field: consumeEffect (Incinerator)
[W] [burner.hjson]: Ignoring unknown field: power (Incinerator)
[W] [charged neptunium.hjson]: Ignoring unknown field: type (Item)
[W] [cryo-missile.hjson]: Ignoring unknown field: shootEffect (Weapon)
[W] [cryo-missile.hjson]: Ignoring unknown field: despawnHit (Weapon)
[W] [cryo-missile.hjson]: Ignoring unknown field: despawnEffect (Weapon)
[W] [cryoflare4.hjson]: Ignoring unknown field: colors (BasicBulletType)
[W] [cryoflare4.hjson]: Ignoring unknown field: collidesFloor (BasicBulletType)
[W] [cryogenic-generator.hjson]: Ignoring unknown field: suffix (DrawLiquidTile)
[W] [cryogenium-missile.hjson]: Ignoring unknown field: shootEffect (Weapon)
[W] [cryogenium-missile.hjson]: Ignoring unknown field: despawnHit (Weapon)
[W] [cryogenium-missile.hjson]: Ignoring unknown field: despawnEffect (Weapon)
[W] [cryogenium.hjson]: Ignoring unknown field: type (Item)
[W] [cryomech.hjson]: Ignoring unknown field: mechStepShake (UnitType)
[W] [cryomech.hjson]: Ignoring unknown field: explodeRange (BasicBulletType)
[W] [cryomech2.hjson]: Ignoring unknown field: mechStepShake (UnitType)
[W] [cryomech2.hjson]: Ignoring unknown field: explodeRange (BasicBulletType)
[W] [cryomech3.hjson]: Ignoring unknown field: mechStepShake (UnitType)
[W] [cryospider4.hjson]: Ignoring unknown field: shots (Weapon)
[W] [diamond.hjson]: Ignoring unknown field: type (Item)
[W] [excisionflare.hjson]: Ignoring unknown field: speed (Weapon)
[W] [flame-missile.hjson]: Ignoring unknown field: collidesGround (UnitType)
[W] [flame-missile.hjson]: Ignoring unknown field: shootEffect (Weapon)
[W] [flame-missile.hjson]: Ignoring unknown field: despawnHit (Weapon)
[W] [flame-missile.hjson]: Ignoring unknown field: despawnEffect (Weapon)
[W] [frozen-message.hjson]: Ignoring unknown field: instructionsPerTick (MessageBlock)
[W] [heater.hjson]: Ignoring unknown field: suffix (DrawLiquidTile)
[W] [ice-shard.hjson]: Ignoring unknown field: type (Item)
[W] [ionized-xenon.hjson]: Ignoring unknown field: cache (Liquid)
[W] [ionized-xenon.hjson]: Ignoring unknown field: parent (Liquid)
[W] [moonstone-missile.hjson]: Ignoring unknown field: shootEffect (Weapon)
[W] [moonstone-missile.hjson]: Ignoring unknown field: despawnHit (Weapon)
[W] [moonstone-missile.hjson]: Ignoring unknown field: despawnEffect (Weapon)
[W] [moonstone.hjson]: Ignoring unknown field: type (Item)
[W] [payload-constructor.hjson]: Ignoring unknown field: craftEffect (Constructor)
[W] [payload-constructor.hjson]: Ignoring unknown field: updateEffect (Constructor)
[W] [pin.hjson]: Ignoring unknown field: burstSpacing (ItemTurret)
[W] [pin.hjson]: Ignoring unknown field: shots (ItemTurret)
[W] [pin.hjson]: Ignoring unknown field: recoilAmount (ItemTurret)
[W] [pin.hjson]: Ignoring unknown field: explodeRange (BasicBulletType)
[W] [reinforced-cryofabric.hjson]: Ignoring unknown field: type (Item)
[W] [repair-field.hjson]: Ignoring unknown field: phase (MendProjector)
[W] [repair-field.hjson]: Ignoring unknown field: color (MendProjector)
[W] [resotank6.hjson]: Ignoring unknown field: collidesFloor (BasicBulletType)
[W] [salmon.hjson]: Ignoring unknown field: hitsize (UnitType)
[W] [shield.hjson]: Ignoring unknown field: hidden (BaseShield)
[W] [xenon.hjson]: Ignoring unknown field: cache (Liquid)
[W] [xenon.hjson]: Ignoring unknown field: parent (Liquid)
[W] [yttrium.hjson]: Ignoring unknown field: type (Item)
[W] Sprite 'eror' in mod 'moon-mod' attempts to override a non-existent sprite. Ignoring.`

...try checking the mindustry docs?

**Comment by yesC48** [comment]
also in Ghetar/The Asylum, you can't place any blocks...
